services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot
    ports:
      - "8080:8080"
    restart: unless-stopped

  test:
    image: golang:1.23.4
    volumes:
      - .:/app
    working_dir: /app
    command: go test -v ./...

  linter:
    image: golangci/golangci-lint:v1.57.2
    volumes:
      - .:/app
    working_dir: /app
    command: golangci-lint run --timeout 1m ./...

